### ISSUE TITLE
can't make it work

### ISSUE THREAD

**Issue by bnicenboim** [manuel-uberti/flymake-proselint#1]
Hi, 
I've installed proselint (and it works from the command line) and this package in doom emacs. But I can't figure out how to activate it.  (I'm quite new to emacs, sorry if this is obvious).

**Comment by manuel-uberti** [comment]
Sorry, I don't use Doom Emacs, but once installed it should be enough to hook it into the modes you want your prose to be linted. The README has an example:

```emacs-lisp
(add-hook 'markdown-mode-hook #'flymake-proselint-setup)
```

Or you can hook it into all your text modes:

```emacs-lisp
(add-hook 'text-mode-hook #'flymake-proselint-setup)
```

No other setup should be required.

**Comment by manuel-uberti** [comment]
It probably makes sense to ping @hlissner on this, who knows better than me if this package needs something more for Doom. :)

**Comment by bnicenboim** [comment]
Thanks for the fast answer, but doom emacs is not that different.  I added the hook, but I don't see any function now with proselint when I do alt-x. (I do see `flymake-proselint-setup`, when I use `describe-function` and the package was installed without errors).
Then I assumed that maybe `flymake-start` or `fly-make-mode` in on will start it, but they don't.
So how should I start it? Or should it be automatic? If so how can I debug it?

**Comment by manuel-uberti** [comment]
Well, you should have `flymake-mode` on as well for this to work. You can try something like this:

```emacs-lisp
(add-hook 'text-mode-hook (lambda ()
                            (flymake-mode +1)
                            (flymake-proselint-setup)))
```

**Comment by manuel-uberti** [comment]
The point of this package is to let Flymake take care of linting your text with `proselint`. Beside setting it up with `flymake-proselint-setup`, you should do nothing more. Flymake (and its related key bindings) will take care of the rest.

I expanded the example in the README to make it more explicit that `flymake-mode` should be on for this to work correctly. I took it for granted that the end user of this package was already using Flymake, my bad. :)

**Comment by bnicenboim** [comment]
Ok thanks! I'll investigate what happens with flymake in my system, and report back.

**Comment by hlissner** [comment]
@bnicenboim Doom doesn't use flymake (it only uses flycheck), so `flymake-mode` won't be enabled by default. Our flycheck module provides proselint integration out of the box though, so you shouldn't need another package, but if you're set on flymake, @manuel-uberti's advice above should work.

I don't know if flymake conflicts with flycheck, however. If they do, you'll need to add `(flycheck-mode -1)` to that hook @manuel-uberti suggested above. Otherwise, disable the `:checker syntax` module.

**Comment by manuel-uberti** [comment]
Thank you @hlissner for the clarification. @bnicenboim you should have all the information you need now.

I am not sure about how Flymake and Flycheck would interact together, but since this now seems not to be related to `flymake-proselint`, I am closing it.
