### ISSUE TITLE
[FEATURE] How to ignore org-todo-keywords?

### ISSUE THREAD

**Issue by Preve92** [manuel-uberti/flymake-proselint#2]
Thanks for this package!  It's straightforward to install and use.  Is it possible to whitelist the org-todo-keywords?

Cheers (:

**Comment by manuel-uberti** [comment]
I do not use Org, so PRs are more than welcome for this.

**Comment by manuel-uberti** [comment]
Thinking about this a bit more, I think it'd be better if you could extend `proselint` to do that. Could you try asking [here](https://github.com/amperser/proselint/issues)?

This package just runs `proselint` and leverage Flymake to display its messages.
